/*DO NOT EDIT THIS FILE*/
#include <fstream>
using namespace std;

class BinSearchTree{
  char symbol;
  BinSearchTree  *lChild;
  BinSearchTree  *rChild;
private:
 public:
 BinSearchTree(char letter) { symbol = letter;lChild = NULL; rChild = NULL;}
  BinSearchTree() { symbol = '0';}
 /*Create a tree with a single node */
  BinSearchTree* buildTree(BinSearchTree *tree, char letter);
  void printTreePreOrder (BinSearchTree *temp, std::ofstream &fp1);
  void printTreeInOrder (BinSearchTree *temp, std::ofstream &fp1);

};
